[package]
name = "gen-readme"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.66"
pulldown-cmark = "0.9.2"
pulldown-cmark-to-cmark = "10.0.4"
serde = { version = "1.0.147", features = ["derive"] }
tinytemplate = "1.2.1"
